# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bayesmax <- function(prior, likelihood, pv) {
    .Call(`_datatrace_bayesmax`, prior, likelihood, pv)
}

poisson_prob <- function(lambda, k) {
    .Call(`_datatrace_poisson_prob`, lambda, k)
}

gauss_prob <- function(m, sig, p) {
    .Call(`_datatrace_gauss_prob`, m, sig, p)
}

bayesmax_mfr <- function(prior, mfr, pv) {
    .Call(`_datatrace_bayesmax_mfr`, prior, mfr, pv)
}

mutual_info <- function(response, nresponseBins, stimulus, nstim, minStimOccurrence) {
    .Call(`_datatrace_mutual_info`, response, nresponseBins, stimulus, nstim, minStimOccurrence)
}

mutual_info2D <- function(response, nresponseBins, stimulus_x, stimulus_y, nstim_x, nstim_y, minStimOccurrence, kernelSize, gaussianVar) {
    .Call(`_datatrace_mutual_info2D`, response, nresponseBins, stimulus_x, stimulus_y, nstim_x, nstim_y, minStimOccurrence, kernelSize, gaussianVar)
}

mutual_info_with_shuffles <- function(response, nresponseBins, stimulus, nstim, trialEnds, nshuffles, shuffleChunkLength, minStimOccurrence) {
    .Call(`_datatrace_mutual_info_with_shuffles`, response, nresponseBins, stimulus, nstim, trialEnds, nshuffles, shuffleChunkLength, minStimOccurrence)
}

create_mfr_model <- function(bin_x, bin_y, nbins_x, nbins_y, trace, minOccupancy) {
    .Call(`_datatrace_create_mfr_model`, bin_x, bin_y, nbins_x, nbins_y, trace, minOccupancy)
}

calcPlaceField <- function(bin_x, bin_y, nbins_x, nbins_y, trace, binnedTrace, minOccupancy, kernelSize, gaussianVar) {
    .Call(`_datatrace_calcPlaceField`, bin_x, bin_y, nbins_x, nbins_y, trace, binnedTrace, minOccupancy, kernelSize, gaussianVar)
}

placeFieldStatsForShuffled <- function(bin_x, bin_y, nbins_x, nbins_y, trace, binnedTrace, trialEnds, nshuffles, minShift, minOccupancy, kernelSize, gaussianVar) {
    .Call(`_datatrace_placeFieldStatsForShuffled`, bin_x, bin_y, nbins_x, nbins_y, trace, binnedTrace, trialEnds, nshuffles, minShift, minOccupancy, kernelSize, gaussianVar)
}

createGaussianKernel <- function(kernelSize, var) {
    .Call(`_datatrace_createGaussianKernel`, kernelSize, var)
}

convolve <- function(M, k) {
    .Call(`_datatrace_convolve`, M, k)
}

isRunning <- function(df, min_run_velocity, mean_run_velocity, window_dur_ms) {
    .Call(`_datatrace_isRunning`, df, min_run_velocity, mean_run_velocity, window_dur_ms)
}

chunkShuffle <- function(trace, trialEnds, shuffleChunkLength) {
    .Call(`_datatrace_chunkShuffle`, trace, trialEnds, shuffleChunkLength)
}

randomShift <- function(trace, trialEnds, minShift) {
    .Call(`_datatrace_randomShift`, trace, trialEnds, minShift)
}

