# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bayesmax <- function(prior, likelihood, pv) {
    .Call(`_datatrace_bayesmax`, prior, likelihood, pv)
}

poisson_prob <- function(lambda, k) {
    .Call(`_datatrace_poisson_prob`, lambda, k)
}

gauss_prob <- function(m, sig, p) {
    .Call(`_datatrace_gauss_prob`, m, sig, p)
}

bayesmax_mfr <- function(prior, mfr, pv) {
    .Call(`_datatrace_bayesmax_mfr`, prior, mfr, pv)
}

mutual_info <- function(response, nresponseBins, stimulus, nstim) {
    .Call(`_datatrace_mutual_info`, response, nresponseBins, stimulus, nstim)
}

mutual_info_with_shuffles <- function(response, nresponseBins, stimulus, nstim, trialEnds, nshuffles, shuffleChunkLength) {
    .Call(`_datatrace_mutual_info_with_shuffles`, response, nresponseBins, stimulus, nstim, trialEnds, nshuffles, shuffleChunkLength)
}

calcPlaceField <- function(bin_xy, nstim, trace, binnedTrace, trialEnds, nshuffles, shuffleChunkLength, minOccupancy) {
    .Call(`_datatrace_calcPlaceField`, bin_xy, nstim, trace, binnedTrace, trialEnds, nshuffles, shuffleChunkLength, minOccupancy)
}

isRunning <- function(df, min_run_velocity, mean_run_velocity, window_dur_ms) {
    .Call(`_datatrace_isRunning`, df, min_run_velocity, mean_run_velocity, window_dur_ms)
}

